---
name: LevelManager
version: 1.0
main: TDroidd\LVLM\Main
api: [1.12.0]
author: TonyDroidd
description: Manage your levels

commands:
    levelmanager:
        permission: levelmanager.command
        description: Manage your levels
        aliases: [lm, lvm]

permissions:
    levelmanager.command:
        description: Use command
        default: op